### ISSUE TITLE
File Audit Handler "log.file.location" setting

### ISSUE THREAD

**Issue by najeebu1** [audit4j/audit4j-spring#7]
The Spring4jAuditConfig class which gets loaded on server startup does not configure the File Audit handler properly, as it (Spring4jAuditConfig) does not have a Map member variable ("properties") which could store the value for "log.file.location" property. 

The file Audit handler needs the above property value, while it is creating the AuditFileWriter instance, during its init method (See line 75 of FileAuditHandler.java) 
writer = new ZeroCopyFileWriter(getProperty("log.file.location"));

To fix this issue, we need to set the properties needed by the FileAuditHandler, before its init method is called (Line 358 of Context.java). For this purpose, the configContext (static instance of  ConcurrentConfigurationContext) should be set with the "properties"(Map) value, before the initHandlers is called (line 146-155 of Context.java). This would need Spring4jAuditConfig to have a Map member variable "properties", which reads the value from the spring config and sets it appropriately, further passing this value to configContext (static instance of  ConcurrentConfigurationContext) - which is used during the initialization of fileAuditHandler.

I will be raising a MR for this shortly.

Note: The console audit handler and the db audit handler work just fine. It is to be noted the DatabaseAuditHandler.java employs a different strategy to set the DB specific properties. Instead of setting the properties (Map) variable defined in the parent Handler class, it defined individual properties in the child class (DatabaseAuditHandler.java) and sets these properties via the spring config.

**Comment by najeebu1** [comment]
Below is the NPE stack trace - thrown when Audit4j tries to log the events to the file.

java.io.FileNotFoundException: **null**\Audit_Log-2017-10-31.audit (The system cannot find the path specified)
        at java.io.RandomAccessFile.open(Native Method)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:236)
        at org.audit4j.core.handler.file.ZeroCopyFileWriter.write(ZeroCopyFileWriter.java:95)
        at org.audit4j.core.handler.file.ZeroCopyFileWriter.write(ZeroCopyFileWriter.java:42)
        at org.audit4j.core.handler.file.FileAuditHandler.handle(FileAuditHandler.java:107)
        at org.audit4j.core.AuditEventProcessor.executeHandlers(AuditEventProcessor.java:73)
        at org.audit4j.core.AuditEventProcessor.process(AuditEventProcessor.java:57)
        at org.audit4j.core.io.AuditProcessOutputStream.write(AuditProcessOutputStream.java:57)
        at org.audit4j.core.io.AuditProcessOutputStream.write(AuditProcessOutputStream.java:32)
        at org.audit4j.core.io.AsyncAuditOutputStream$1.accept(AsyncAuditOutputStream.java:78)
        at org.audit4j.core.io.AsyncAuditOutputStream$1.accept(AsyncAuditOutputStream.java:75)
        at reactor.function.support.Boundary$1.accept(Boundary.java:67)
        at reactor.core.action.CallbackAction.doAccept(CallbackAction.java:36)
        at reactor.core.action.Action.accept(Action.java:52)
        at reactor.core.action.Action.accept(Action.java:32)
        at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:73)
        at reactor.event.routing.ConsumerFilteringEventRouter.route(ConsumerFilteringEventRouter.java:78)
        at reactor.event.dispatch.AbstractLifecycleDispatcher.route(AbstractLifecycleDispatcher.java:64)
        at reactor.event.dispatch.AbstractSingleThreadDispatcher$SingleThreadTask.run(AbstractSingleThreadDispatcher.java:50)
        at reactor.event.dispatch.RingBufferDispatcher$3.onEvent(RingBufferDispatcher.java:115)
        at reactor.event.dispatch.RingBufferDispatcher$3.onEvent(RingBufferDispatcher.java:112)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
